### PR TITLE
ASP.Net 7.0 C# Backend

### PR DESCRIPTION
**Pull request by markhiserodt**

### CODE REVIEW

**Comment by SOSharkie** [comment]
When running `ng serve` in the ClientApp I'm seeing 3 vulnerabilities (1 moderate, 1 high, 1 critical) as well as 2 deprecation warnings. Can we fix these if not too hard? Just trying to prevent building early tech debt

**Comment by SOSharkie** [comment]
Also can you remove the `.angular/cache` folder and all the files in there, its in the .gitignore file so shouldn't be part of the repo

**Comment by markhiserodt** [comment]
> Also can you remove the `.angular/cache` folder and all the files in there, its in the .gitignore file so shouldn't be part of the repo

not sure what you're talking about. There is no .angular folder in this branch/pull request or in master either

**Comment by markhiserodt** [comment]
you may just need to delete it from your local checkout of the branch since directory paths probably got messed up. And after this merge, I would recommend deleting your local repo and re-cloning and re-building node_modules

**Comment by SOSharkie** [comment]
> you may just need to delete it from your local checkout of the branch since directory paths probably got messed up. And after this merge, I would recommend deleting your local repo and re-cloning and re-building node_modules

Ahh okay yeah looks like thats what happened.

**Review by SOSharkie — APPROVED** [review]
LGTM

**Pull request merged**
